name = "arbor-aid-tree"
main = "src/worker.js"
compatibility_date = "2024-06-01"

pages_build_output_dir = "public"

[[d1_databases]]
binding = "ARBOR_AID_DB"
database_name = "arbor-aid"
database_id = "c2d26da4-4965-4641-b997-53eea5a8ee8e"
